# Generated by Django 5.0.4 on 2024-05-17 18:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='actually_tether',
        ),
        migrations.AddField(
            model_name='deposit',
            name='crypto_type',
            field=models.CharField(default='USDT (BEP20)', max_length=100),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 18, 13, 56, 834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawemailconfirmation',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 18, 18, 56, 1566, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tether', models.CharField(max_length=100)),
                ('wallet', models.CharField(max_length=500)),
                ('crypto_type', models.CharField(default='USDT (BEP20)', max_length=100)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_at', models.DateTimeField(default=datetime.datetime(2024, 5, 17, 19, 13, 56, 1215, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduledDepositCheck',
        ),
    ]
