# Generated by Django 5.0.4 on 2024-07-12 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_deposit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 11, 17, 45, 244940, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 12, 17, 45, 247426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawemailconfirmation',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 11, 22, 45, 247825, tzinfo=datetime.timezone.utc)),
        ),
    ]
