# Generated by Django 5.0.4 on 2024-07-12 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_deposit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 11, 49, 54, 111975, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 12, 49, 54, 112278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawemailconfirmation',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 11, 54, 54, 112577, tzinfo=datetime.timezone.utc)),
        ),
    ]
