# Generated by Django 5.0.4 on 2024-07-12 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeVolume24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='volume', max_length=10)),
                ('number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChartPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='token', max_length=10)),
                ('number', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NumberChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('open', models.FloatField(blank=True, db_column='open_value', null=True)),
                ('high', models.FloatField(blank=True, db_column='high_value', null=True)),
                ('low', models.FloatField(blank=True, db_column='low_value', null=True)),
                ('close', models.FloatField(blank=True, db_column='close_value', null=True)),
                ('my_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.chartprice')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledNumberChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('run_at', models.DateTimeField()),
                ('my_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.chartprice')),
            ],
        ),
    ]
