# Generated by Django 5.0.4 on 2024-07-12 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_changepasswordemailconfirmation_expiration_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepasswordemailconfirmation',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 11, 22, 45, 231444, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 11, 22, 45, 231206, tzinfo=datetime.timezone.utc)),
        ),
    ]
