# Generated by Django 5.0.4 on 2024-07-12 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_changepasswordemailconfirmation_expiration_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepasswordemailconfirmation',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 12, 42, 56, 753254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='expiration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 12, 42, 56, 752951, tzinfo=datetime.timezone.utc)),
        ),
    ]
